#!/bin/sh
set -e

# going to the root of the repo
cd $(git rev-parse --show-toplevel)

if [ -e package.json ]; then
  npm run test
elif [ -e pom.xml ]; then
  mvn clean install -Penable-clover
fi

exit 0
